type LookupData {
  CIG: CIGLookups
  UEX: UEXLookups
  loadout: JSONObject
}

"""
These are the names of the reports that we generate for the SurveyCorps
"""
enum SurveyDataReports {
  vehicleProbs
  shipOreByGravProb
  shipOreByRockClassProb
  shipRockClassByGravProb
  bonusMap
  leaderBoard
}

type CIGLookups {
  densitiesLookups: JSONObject
  methodsBonusLookup: JSONObject
  oreProcessingLookup: JSONObject
  refineryBonusLookup: JSONObject
}

type UEXLookups {
  bodies: JSONObject
  maxPrices: JSONObject
  ships: JSONObject
  tradeports: JSONObject
}

enum AuthTypeEnum {
  GOOGLE
  DISCORD
  API_KEY
}

enum LookupTypeEnum {
  CIG
  UEX
}